language: java

addons:
  sonarcloud:
    organization: "afcabezasq"
    token:
      secure: "53f5c9547702c2124cfffee4b9dd31d7b3bb9b1a" # encrypted value of your token

before_install: cd helloWorld
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=afcabezasq_ec2-repo